Repository openedx/frontend-app-gradebook, pull requests merged in 2021-12, with the labels that each got.

#219 docs: Describe messages descriptions better
  src/components/GradesView/BulkManagementControls.messages.js
  src/components/GradesView/FilterMenuToggle.messages.js
  src/components/GradesView/ImportGradesButton.messages.js
  src/components/GradesView/ImportSuccessToast.messages.js
  src/components/GradesView/InterventionsReport.messages.js
  src/components/GradesView/ScoreViewInput.messages.js
  src/components/GradesView/SearchControls.messages.js
  src/components/GradesView/StatusAlerts.messages.js
  src/components/GradesView/__snapshots__/FilterMenuToggle.test.jsx.snap
  src/components/GradesView/__snapshots__/ImportGradesButton.test.jsx.snap
  src/components/GradesView/__snapshots__/InterventionsReport.test.jsx.snap
  src/components/GradesView/__snapshots__/ScoreViewInput.test.jsx.snap
  src/components/GradesView/__snapshots__/SearchControls.test.jsx.snap
  src/components/GradesView/__snapshots__/StatusAlerts.test.jsx.snap
  src/data/constants/filters.messages.js
Labels: open-source-contribution, community manager review

#218 feat: add compatibility with transifex
  .gitignore
  .tx/config
  src/i18n/messages/ar.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fr.json
  src/i18n/messages/zh_CN.json
  src/i18n/transifex_input.json
Labels: open-source-contribution, waiting on author, core committer

#221 fix: build the course_id properly when MFE is deployed in a subdirectory
  src/data/services/lms/urls.js
Labels: needs triage, open-source-contribution

#222 feat: enabling header override
  .env.development
  package-lock.json
  package.json
  src/App.jsx
  src/App.scss
  src/App.test.jsx
  src/__snapshots__/App.test.jsx.snap
  src/index.jsx
  src/index.test.jsx
Labels: needs triage, open-source-contribution

#213 fix: build the course id properly when MFE is deployed in a subdirectory
  src/data/services/lms/urls.js
Labels: open-source-contribution, engineering review

#220 feat: enabling header override
  .env.development
  package-lock.json
  package.json
  src/App.jsx
  src/App.scss
  src/App.test.jsx
  src/__snapshots__/App.test.jsx.snap
  src/index.jsx
  src/index.test.jsx
Labels: open-source-contribution, awaiting prioritization
