Repository openedx/frontend-app-gradebook, pull requests merged in 2023-01, with the labels that each got.

#274 Automate Browserlist DB Update
  .github/workflows/update-browserslist-db.yml
Labels: engineering review

#279 Feature: Persian language Support
  Makefile
  src/i18n/index.jsx
  src/i18n/messages/fa_IR.json
Labels: open-source-contribution

#277 fix: correct grades minmax values
  src/data/selectors/index.js
  src/data/selectors/index.test.js
Labels: open-source-contribution, changes requested, waiting on author

#303 fix: correct grades minmax values
  src/data/selectors/index.js
  src/data/selectors/index.test.js
Labels: open-source-contribution, changes requested

#254 refactor: upgraded frontend-build version to v12
  .eslintrc.js
  package-lock.json
  src/components/GradesView/FilterBadges/test.jsx
  src/components/GradesView/GradebookTable/Fields.jsx
  src/data/reducers/app.js
  src/data/reducers/assignmentTypes.js
  src/data/reducers/cohorts.js
  src/data/reducers/config.js
  src/data/reducers/filters.js
  src/data/reducers/grades.js
  src/data/reducers/roles.js
  src/data/reducers/tracks.js
Labels: engineering review

#264 feat: add a simple validation to the adjusted grade field
  src/components/GradesView/EditModal/OverrideTable/AdjustedGradeInput.jsx
  src/components/GradesView/EditModal/OverrideTable/AdjustedGradeInput.test.jsx
  src/components/GradesView/EditModal/OverrideTable/__snapshots__/AdjustedGradeInput.test.jsx.snap
Labels: open-source-contribution, product review, waiting on author

#307 feat: add a simple validation to the adjusted grade field
  src/components/GradesView/EditModal/OverrideTable/AdjustedGradeInput.jsx
  src/components/GradesView/EditModal/OverrideTable/AdjustedGradeInput.test.jsx
  src/components/GradesView/EditModal/OverrideTable/__snapshots__/AdjustedGradeInput.test.jsx.snap
Labels: open-source-contribution
