Repository openedx/frontend-app-gradebook, pull requests merged in 2024-04, with the labels that each got.

#363 fix: fix sidebar scrolling and adaptation for mobile
  src/components/GradebookHeader/__snapshots__/index.test.jsx.snap
  src/components/GradebookHeader/index.jsx
  src/components/GradesView/FilterMenuToggle/__snapshots__/index.test.jsx.snap
  src/components/GradesView/FilterMenuToggle/index.jsx
  src/components/GradesView/GradesView.scss
  src/components/GradesView/SearchControls/__snapshots__/index.test.jsx.snap
  src/components/GradesView/SearchControls/index.jsx
  src/components/GradesView/__snapshots__/index.test.jsx.snap
  src/components/GradesView/index.jsx
Labels: open-source-contribution, product review complete

#370 fix: fix sidebar scrolling and adaptation for mobile
  src/components/GradebookHeader/__snapshots__/index.test.jsx.snap
  src/components/GradebookHeader/index.jsx
  src/components/GradesView/FilterMenuToggle/__snapshots__/index.test.jsx.snap
  src/components/GradesView/FilterMenuToggle/index.jsx
  src/components/GradesView/GradesView.scss
  src/components/GradesView/SearchControls/__snapshots__/index.test.jsx.snap
  src/components/GradesView/SearchControls/index.jsx
  src/components/GradesView/__snapshots__/index.test.jsx.snap
  src/components/GradesView/index.jsx
Labels: open-source-contribution, backport, product review complete

#362 fix: fix sidebar scrolling and adaptation for mobile
  src/components/GradebookHeader/__snapshots__/test.jsx.snap
  src/components/GradebookHeader/index.jsx
  src/components/GradesView/FilterMenuToggle.jsx
  src/components/GradesView/GradesView.scss
  src/components/GradesView/SearchControls.jsx
  src/components/GradesView/__snapshots__/FilterMenuToggle.test.jsx.snap
  src/components/GradesView/__snapshots__/SearchControls.test.jsx.snap
  src/components/GradesView/__snapshots__/test.jsx.snap
  src/components/GradesView/index.jsx
Labels: open-source-contribution, backport, product review complete

#387 fix: "An unexpected error occurred" after second opening any grade
  src/components/GradesView/EditModal/OverrideTable/hooks.js
Labels: open-source-contribution

#386 fix: "An unexpected error occurred" after second opening any grade
  src/components/GradesView/EditModal/OverrideTable/hooks.js
Labels: open-source-contribution, backport
