Repository openedx/frontend-app-gradebook, pull requests merged in 2024-05, with the labels that each got.

#390 fix: Grade value is displayed in the modal
  src/components/GradesView/EditModal/ModalHeaders.jsx
  src/components/GradesView/EditModal/ModalHeaders.test.jsx
Labels: bug, open-source-contribution

#393 chore: Adds catalog-info.yml for the project
  catalog-info.yaml
Labels: open-source-contribution

#310 fix: Fix rows counter in the Edit Grade modal window
  src/components/GradesView/EditModal/OverrideTable/__snapshots__/index.test.jsx.snap
  src/components/GradesView/EditModal/OverrideTable/index.jsx
Labels: open-source-contribution, product review complete
